import type { NextPage } from 'next'
import Head from "next/head";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <h1>Index page</h1>
            </div>
        </>
    )
}

export default Home
